In [27]:
import os
import numpy as np
from tqdm.notebook import tqdm
from skimage.io import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import load_img, img_to_array



In [28]:
# Define the CNN model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(36, activation='softmax'))  # Adjusted output layer to match number of classes

In [29]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [30]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 126, 126, 32)      896       
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 63, 63, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_13 (Conv2D)          (None, 61, 61, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPoolin  (None, 30, 30, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_14 (Conv2D)          (None, 28, 28, 128)       73856     
                                                                 
 max_pooling2d_8 (MaxPoolin  (None, 14, 14, 128)      

In [31]:
data_dir = r'C:\Users\shilp\OneDrive\Desktop\Sign language\Data'
categories = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

X = []
Y = []

for category in tqdm(categories):
    folder_path = os.path.join(data_dir, category)
    for img_name in os.listdir(folder_path):
        img_path = os.path.join(folder_path, img_name)
        img = load_img(img_path, target_size=(128, 128))  # Load and resize image
        img = img_to_array(img) / 255.0  # Convert image to array and normalize
        X.append(img)
        Y.append(categories.index(category))

X = np.array(X)
Y = np.array(Y)

  0%|          | 0/26 [00:00<?, ?it/s]

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train

array([[[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        ...,

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]

In [33]:
X_test

array([[[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],

        ...,

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]

In [34]:
Y_train

array([17,  2,  0, ...,  2, 24, 23])

In [35]:
Y_test

array([15,  2, 12, ..., 20, 18,  9])

In [36]:
#X_train=np.array(X_train)
#X_test=np.array(X_test)
#Y_train=np.array(Y_train)
#Y_test=np.array(Y_test)

In [37]:
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)

In [38]:
history = model.fit(datagen.flow(X_train, Y_train, batch_size=32), epochs=10, validation_data=(X_test, Y_test))

Epoch 1/10
199/199 [==============================] - 86s 430ms/step - loss: 2.3019 - accuracy: 0.2818 - val_loss: 0.9708 - val_accuracy: 0.6388
Epoch 2/10
199/199 [==============================] - 112s 560ms/step - loss: 0.8895 - accuracy: 0.6946 - val_loss: 0.2912 - val_accuracy: 0.9121
Epoch 3/10
199/199 [==============================] - 112s 560ms/step - loss: 0.4226 - accuracy: 0.8516 - val_loss: 0.1303 - val_accuracy: 0.9435
Epoch 4/10
199/199 [==============================] - 109s 545ms/step - loss: 0.2885 - accuracy: 0.9006 - val_loss: 0.0451 - val_accuracy: 0.9881
Epoch 5/10
199/199 [==============================] - 147s 737ms/step - loss: 0.2133 - accuracy: 0.9288 - val_loss: 0.0505 - val_accuracy: 0.9931
Epoch 6/10
199/199 [==============================] - 125s 629ms/step - loss: 0.1853 - accuracy: 0.9367 - val_loss: 0.0768 - val_accuracy: 0.9874
Epoch 7/10
199/199 [==============================] - 112s 564ms/step - loss: 0.1275 - accuracy: 0.9527 - val_loss: 0.0260 - 

In [39]:
test_loss, test_accuracy = model.evaluate(X_test, Y_test)



50/50 [==============================] - 6s 117ms/step - loss: 0.0104 - accuracy: 0.9975


In [40]:
model.save('keras_model.h5')


C:\Users\shilp\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [44]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

def predict_sign_language_class(image_path, model_path='keras_model.h5'):
    # Load the saved model
    model = load_model(model_path)

    # Load and preprocess the image
    img = image.load_img(image_path, target_size=(128, 128))
    img_array = image.img_to_array(img) / 255.0  # Convert image to array and normalize
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make predictions
    predictions = model.predict(img_array)

    # Get the predicted class
    predicted_class_index = np.argmax(predictions)
    predicted_class = chr(65 + predicted_class_index)  # Convert index to character

    return predicted_class


In [45]:
image_path = r'C:\Users\shilp\OneDrive\Desktop\Sign language\Data\A\Image_1698499705.962042.jpg'
predicted_class = predict_sign_language_class(image_path)
print("Predicted class:", predicted_class)

1/1 [==============================] - 0s 68ms/step
Predicted class: A


In [46]:
image_path = r"C:\Users\shilp\OneDrive\Desktop\Sign language\Data\B\Image_1698501383.3889585.jpg"
predicted_class = predict_sign_language_class(image_path)
print("Predicted class:", predicted_class)

1/1 [==============================] - 0s 84ms/step
Predicted class: B
